### ISSUE TITLE
Wrong return type on numberFormat and numberFormatAsync

### ISSUE THREAD

**Issue by hyperremix** [shystruk/react-native-android-currency-formatter#1]
Hello and thanks for creating this package!

Right now numberFormat and numberFormatAsync return `number` and `Promise<number>` respectively. This should probably be `string` and `Promise<string>` instead since that is what is returned from the native module.

Best regards,
Fredrik

**Comment by shystruk** [comment]
Hi @hyperremix 
Good catch. Thank you for reporting this 👍

**Comment by shystruk** [comment]
close at https://github.com/shystruk/react-native-android-currency-formatter/commit/82dd39cd22126368935f2bf99b034c39cdf02049
